version: '3'
services:
  express:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
      - REDIS_URL=redis://redis:6379

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  mongodb_data:
  redis_data: